// <auto-generated />
namespace SchoolManagement.Concrete.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addIsdelete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addIsdelete));
        
        string IMigrationMetadata.Id
        {
            get { return "202212081904331_addIsdelete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
