// <auto-generated />
namespace SchoolManagement.Concrete.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SessionExamAddNames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SessionExamAddNames));
        
        string IMigrationMetadata.Id
        {
            get { return "202211231843520_SessionExamAddNames"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
